package dev.jotalac.core.ui.theme.colors

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object DefaultColors {
    val primaryLight = Color(0xFF904B3D)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFFFDAD3)
    val onPrimaryContainerLight = Color(0xFF733428)
    val secondaryLight = Color(0xFF775750)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFFFDAD3)
    val onSecondaryContainerLight = Color(0xFF5D3F3A)
    val tertiaryLight = Color(0xFF6E5C2E)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFF9E0A6)
    val onTertiaryContainerLight = Color(0xFF554519)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF8F6)
    val onBackgroundLight = Color(0xFF231918)
    val surfaceLight = Color(0xFFFFF8F6)
    val onSurfaceLight = Color(0xFF231918)
    val surfaceVariantLight = Color(0xFFF5DDD9)
    val onSurfaceVariantLight = Color(0xFF534340)
    val outlineLight = Color(0xFF85736F)
    val outlineVariantLight = Color(0xFFD8C2BD)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF392E2C)
    val inverseOnSurfaceLight = Color(0xFFFFEDE9)
    val inversePrimaryLight = Color(0xFFFFB4A5)
    val surfaceDimLight = Color(0xFFE8D6D3)
    val surfaceBrightLight = Color(0xFFFFF8F6)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFFF0EE)
    val surfaceContainerLight = Color(0xFFFCEAE6)
    val surfaceContainerHighLight = Color(0xFFF7E4E1)
    val surfaceContainerHighestLight = Color(0xFFF1DFDB)

    val primaryDark = Color(0xFFFFB4A5)
    val onPrimaryDark = Color(0xFF561E14)
    val primaryContainerDark = Color(0xFF733428)
    val onPrimaryContainerDark = Color(0xFFFFDAD3)
    val secondaryDark = Color(0xFFE7BDB5)
    val onSecondaryDark = Color(0xFF442A24)
    val secondaryContainerDark = Color(0xFF5D3F3A)
    val onSecondaryContainerDark = Color(0xFFFFDAD3)
    val tertiaryDark = Color(0xFFDCC48C)
    val onTertiaryDark = Color(0xFF3D2E04)
    val tertiaryContainerDark = Color(0xFF554519)
    val onTertiaryContainerDark = Color(0xFFF9E0A6)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF1A1110)
    val onBackgroundDark = Color(0xFFF1DFDB)
    val surfaceDark = Color(0xFF1A1110)
    val onSurfaceDark = Color(0xFFF1DFDB)
    val surfaceVariantDark = Color(0xFF534340)
    val onSurfaceVariantDark = Color(0xFFD8C2BD)
    val outlineDark = Color(0xFFA08C89)
    val outlineVariantDark = Color(0xFF534340)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFF1DFDB)
    val inverseOnSurfaceDark = Color(0xFF392E2C)
    val inversePrimaryDark = Color(0xFF904B3D)
    val surfaceDimDark = Color(0xFF1A1110)
    val surfaceBrightDark = Color(0xFF423734)
    val surfaceContainerLowestDark = Color(0xFF140C0B)
    val surfaceContainerLowDark = Color(0xFF231918)
    val surfaceContainerDark = Color(0xFF271D1B)
    val surfaceContainerHighDark = Color(0xFF322826)
    val surfaceContainerHighestDark = Color(0xFF3D3230)
}


internal val defaultLightScheme = lightColorScheme(
    primary = DefaultColors.primaryLight,
    onPrimary = DefaultColors.onPrimaryLight,
    primaryContainer = DefaultColors.primaryContainerLight,
    onPrimaryContainer = DefaultColors.onPrimaryContainerLight,
    secondary = DefaultColors.secondaryLight,
    onSecondary = DefaultColors.onSecondaryLight,
    secondaryContainer = DefaultColors.secondaryContainerLight,
    onSecondaryContainer = DefaultColors.onSecondaryContainerLight,
    tertiary = DefaultColors.tertiaryLight,
    onTertiary = DefaultColors.onTertiaryLight,
    tertiaryContainer = DefaultColors.tertiaryContainerLight,
    onTertiaryContainer = DefaultColors.onTertiaryContainerLight,
    error = DefaultColors.errorLight,
    onError = DefaultColors.onErrorLight,
    errorContainer = DefaultColors.errorContainerLight,
    onErrorContainer = DefaultColors.onErrorContainerLight,
    background = DefaultColors.backgroundLight,
    onBackground = DefaultColors.onBackgroundLight,
    surface = DefaultColors.surfaceLight,
    onSurface = DefaultColors.onSurfaceLight,
    surfaceVariant = DefaultColors.surfaceVariantLight,
    onSurfaceVariant = DefaultColors.onSurfaceVariantLight,
    outline = DefaultColors.outlineLight,
    outlineVariant = DefaultColors.outlineVariantLight,
    scrim = DefaultColors.scrimLight,
    inverseSurface = DefaultColors.inverseSurfaceLight,
    inverseOnSurface = DefaultColors.inverseOnSurfaceLight,
    inversePrimary = DefaultColors.inversePrimaryLight,
    surfaceDim = DefaultColors.surfaceDimLight,
    surfaceBright = DefaultColors.surfaceBrightLight,
    surfaceContainerLowest = DefaultColors.surfaceContainerLowestLight,
    surfaceContainerLow = DefaultColors.surfaceContainerLowLight,
    surfaceContainer = DefaultColors.surfaceContainerLight,
    surfaceContainerHigh = DefaultColors.surfaceContainerHighLight,
    surfaceContainerHighest = DefaultColors.surfaceContainerHighestLight,
)

internal val defaultDarkScheme = darkColorScheme(
    primary = DefaultColors.primaryDark,
    onPrimary = DefaultColors.onPrimaryDark,
    primaryContainer = DefaultColors.primaryContainerDark,
    onPrimaryContainer = DefaultColors.onPrimaryContainerDark,
    secondary = DefaultColors.secondaryDark,
    onSecondary = DefaultColors.onSecondaryDark,
    secondaryContainer = DefaultColors.secondaryContainerDark,
    onSecondaryContainer = DefaultColors.onSecondaryContainerDark,
    tertiary = DefaultColors.tertiaryDark,
    onTertiary = DefaultColors.onTertiaryDark,
    tertiaryContainer = DefaultColors.tertiaryContainerDark,
    onTertiaryContainer = DefaultColors.onTertiaryContainerDark,
    error = DefaultColors.errorDark,
    onError = DefaultColors.onErrorDark,
    errorContainer = DefaultColors.errorContainerDark,
    onErrorContainer = DefaultColors.onErrorContainerDark,
    background = DefaultColors.backgroundDark,
    onBackground = DefaultColors.onBackgroundDark,
    surface = DefaultColors.surfaceDark,
    onSurface = DefaultColors.onSurfaceDark,
    surfaceVariant = DefaultColors.surfaceVariantDark,
    onSurfaceVariant = DefaultColors.onSurfaceVariantDark,
    outline = DefaultColors.outlineDark,
    outlineVariant = DefaultColors.outlineVariantDark,
    scrim = DefaultColors.scrimDark,
    inverseSurface = DefaultColors.inverseSurfaceDark,
    inverseOnSurface = DefaultColors.inverseOnSurfaceDark,
    inversePrimary = DefaultColors.inversePrimaryDark,
    surfaceDim = DefaultColors.surfaceDimDark,
    surfaceBright = DefaultColors.surfaceBrightDark,
    surfaceContainerLowest = DefaultColors.surfaceContainerLowestDark,
    surfaceContainerLow = DefaultColors.surfaceContainerLowDark,
    surfaceContainer = DefaultColors.surfaceContainerDark,
    surfaceContainerHigh = DefaultColors.surfaceContainerHighDark,
    surfaceContainerHighest = DefaultColors.surfaceContainerHighestDark,
)